services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slavlee\EventlistenerTutorial2\EventListener\HelloworldListener:
      tags:
         - name: event.listener
           identifier: 'HelloworldControllerShowAction'
           event: Slavlee\EventlistenerTutorial\Event\HelloworldControllerShowActionEvent

  Slavlee\EventlistenerTutorial2\EventListener\HelloworldAdditionalInfoListener:
      tags:
         - name: event.listener
           identifier: 'HelloworldControllerShowAdditionalInfoAction'
           event: Slavlee\EventlistenerTutorial\Event\HelloworldControllerShowActionAdditionalInfoEvent         