services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slavlee\EventlistenerTutorial\EventListener\HelloworldListener:
      tags:
         - name: event.listener
           identifier: 'HelloworldControllerShowAction'
           event: Slavlee\EventlistenerTutorial\Event\HelloworldControllerShowActionEvent  